### ISSUE TITLE
can node-expat please use node-pre-gyp?

### ISSUE THREAD

**Issue by Pomax** [astro/node-expat#101]
In order to deal with binary compilation being a total mess, we now have https://www.npmjs.org/package/node-pre-gyp available, which takes care of the compiling part so that users don't need to run the compile themselves. Which is nice, because on windows for instance trying to get node-gyp to work is murder-rage-inducingly hard =)

**Comment by darelf** [comment]
Sorry for poking this.

It's not just integrating node-pre-gyp, which is easy. It's that pre-compiled binaries would need to be hosted somewhere. node-pre-gyp assumes you are hosting on amazon aws, though I suppose that could be changed fairly easily, it still has to be somewhere...

I'd love to see this work, as I could really use this feature in my production environment (since in production we don't have compilers....) to make things simpler.

**Comment by darelf** [comment]
Hey @lloydwatkin 
I guess I also cloned this and added node-pre-gyp support, and it seems to work ( `npm install --build-from-source` works) and to pass `npm test` on my Linux box.  It doesn't set a valid host for storing binaries, so that part obviously won't work.

I've never created branches or pull requests on other people's projects, so I'm unclear on that process, but would be happy to send it over if you want it.

**Comment by lloydwatkin** [comment]
Hi @darelf,

Sounds good, I think we'll need a chat about it (or get overwhelming support from users), I prefer to use OS packages but realise many operating systems don't work so well.

You'll need to create a fork (click 'fork' at the top of this page). Then add your repo as another git source - so in my case it would be ```git remote add myrepo git@github.com:lloydwatkin/node-expat.git```. You can then branch your copy ```git checkout -b node-gyp-pre```, then push to your repo, ``` git push my-repo node-gyp-pre```. Navigate to your fork on github and it'll then usually give you a banner to create a pull request back to the project. If you get stuck please let me know.

/cc @chris-rock @sonnyp

**Comment by darelf** [comment]
Hmm... well, I submitted #116 and then noticed the travis build fails for 0.12. But I guess it does that for all your commits, and since I have no problems on my local linux box using 0.12.2 then I suppose it's not a true issue.

**Comment by Pomax** [comment]
that could be an issue with package.json dependencies - some older deps don't work with 0.12, but do when they're `uninstall --save`'d and then re`install --save`d
