### ISSUE TITLE
Project link http://node-xmpp.org/doc/expat.html dead?

### ISSUE THREAD

**Issue by hartwork** [astro/node-expat#174]
It seems like the project link http://node-xmpp.org/doc/expat.html seems to point to a domain that no longer exists?

**Comment by astro** [comment]
cc: @sonnyp @lloydwatkin

**Comment by sonnyp** [comment]
Sorry about that I forgot node-expat had a documentation on node-xmpp website.

I'm working on a new website for node-xmpp, for simplicity and because the website was pretty short I didn't plan on getting it back online before the new one which should happen this weekend.

Since node-expat isn't part of node-xmpp anymore I think we shouldn't include node-expat documentation there, what do you think?

**Comment by sonnyp** [comment]
Double checked, actually I removed expat and stringprep documentation from the website a year ago

See https://github.com/node-xmpp/node-xmpp.github.io/commit/889096487f2fb4b97bdd9ede3236b2293d2d05f6

**Comment by astro** [comment]
Ok, removed the links.
